INSERT
INTO BANQUETS.EMPLOYEE
VALUES (9, 'Андрей', 'Головацкий', 'официант', '89048902345');

SELECT NAME, SURNAME
FROM BANQUETS.EMPLOYEE
WHERE EMPLOYEE_TYPE = 'официант';

UPDATE BANQUETS.EMPLOYEE
SET EMPLOYEE_TYPE = 'повар'
WHERE NAME = 'Андрей';

DELETE
FROM BANQUETS.EMPLOYEE
WHERE SURNAME = 'Головацкий';



INSERT
INTO BANQUETS.DISH
VALUES (21, 'шаурма', 180);

SELECT DISH_NAME
FROM BANQUETS.DISH
WHERE COST <= 300;

UPDATE BANQUETS.DISH
SET COST = 1000
WHERE DISH_NAME = 'шаурма';

DELETE
FROM BANQUETS.DISH
WHERE DISH_NAME = 'шаурма';



INSERT
INTO BANQUETS.CUSTOMER
VALUES (6, 'Маргарита', 'Кулигина', '89017683456');

SELECT SURNAME
FROM BANQUETS.CUSTOMER
WHERE SURNAME LIKE 'З%';

UPDATE BANQUETS.CUSTOMER
SET PHONE_NUMBER = '89991112345'
WHERE NAME = 'Маргарита';

DELETE
FROM BANQUETS.CUSTOMER
WHERE NAME = 'Маргарита';



INSERT
INTO BANQUETS.EVENT
VALUES (7, 5, 'юбилей', '2020-07-03 15:00', 40, 1, '15:00',
        '15:40', '17:40', '23:00', false, 300000, false);

SELECT EVENT_ID
FROM BANQUETS.EVENT
WHERE SUM >= 90000 AND PAYMENT_STATUS = true;

UPDATE BANQUETS.EVENT
SET SUM = 30000
WHERE EVENT_ID = 7;

DELETE
FROM BANQUETS.EVENT
WHERE EVENT_ID = 7;



INSERT
INTO BANQUETS.EVENT
VALUES (8, 1, 'свадьба', '2021-08-13 12:00', 30, 1, '12:00',
        '12:20', '14:20', '22:00', false, 75000, true);

SELECT EVENT_TYPE, EVENT_DTTM
FROM BANQUETS.EVENT
WHERE GUESTS_NUMBER >= 50;

UPDATE BANQUETS.EVENT
SET GUESTS_NUMBER = 90
WHERE EVENT_ID = 8;

DELETE
FROM BANQUETS.EVENT
WHERE EVENT_ID = 8;



INSERT
INTO BANQUETS.EMPLOYEE_X_EVENT
VALUES (4, 6);

SELECT EMPLOYEE_ID
FROM BANQUETS.EMPLOYEE_X_EVENT
WHERE EVENT_ID = 3;

UPDATE BANQUETS.EMPLOYEE_X_EVENT
SET EMPLOYEE_ID = 2
WHERE EMPLOYEE_ID = 4 AND EVENT_ID = 6;

DELETE
FROM BANQUETS.EMPLOYEE_X_EVENT
WHERE EMPLOYEE_ID = 2 AND EVENT_ID = 6;



INSERT
INTO BANQUETS.TABLE
VALUES ('6_6', 6, 0);

SELECT TABLE_ID
FROM BANQUETS.TABLE
WHERE PLACES_NUMBER = 10;

UPDATE BANQUETS.TABLE
SET PLACES_NUMBER = 1
WHERE TABLE_ID = '6_6';

DELETE
FROM BANQUETS.TABLE
WHERE TABLE_ID = '6_6';



INSERT
INTO BANQUETS.TABLE_X_DISH
VALUES ('6_5', 19, 1, 'общее');

SELECT DISH_ID
FROM BANQUETS.TABLE_X_DISH
WHERE TABLE_ID = '1_1' AND DISH_TYPE = 'общее';

UPDATE BANQUETS.TABLE_X_DISH
SET DISHES_NUMBER = 8
WHERE TABLE_ID = '6_5' AND DISH_ID = 19;

DELETE
FROM BANQUETS.TABLE_X_DISH
WHERE TABLE_ID = '6_5' AND DISH_ID = 19;

