CREATE INDEX ON BANQUETS.CUSTOMER(CUSTOMER_ID);

CREATE INDEX ON BANQUETS.DISH(DISH_ID);

CREATE INDEX ON BANQUETS.CUSTOMER(CUSTOMER_ID);

CREATE INDEX ON BANQUETS.EMPLOYEE(EMPLOYEE_ID);

CREATE INDEX ON BANQUETS.EMPLOYEE_X_EVENT(EMPLOYEE_ID);
CREATE INDEX ON BANQUETS.EMPLOYEE_X_EVENT(EVENT_ID);

CREATE INDEX ON BANQUETS.EVENT(EVENT_ID);
CREATE INDEX ON BANQUETS.EVENT(CUSTOMER_ID);

CREATE INDEX ON BANQUETS.TABLE(TABLE_ID);
CREATE INDEX ON BANQUETS.TABLE(EVENT_ID);

CREATE INDEX ON BANQUETS.TABLE_X_DISH(TABLE_ID);
CREATE INDEX ON BANQUETS.TABLE_X_DISH(DISH_ID);