DROP SCHEMA IF EXISTS BANQUETS CASCADE;

CREATE SCHEMA BANQUETS;

CREATE TABLE BANQUETS.EMPLOYEE(
    EMPLOYEE_ID     SERIAL PRIMARY KEY,
    NAME            VARCHAR(50),
    SURNAME         VARCHAR(50),
    EMPLOYEE_TYPE   VARCHAR(50),
    PHONE_NUMBER    VARCHAR(20),
    CONSTRAINT ALL_EMPLOYEE_TYPES
    CHECK (EMPLOYEE_TYPE IN ('официант', 'повар', 'посудомойщик'))
);

CREATE TABLE BANQUETS.DISH(
    DISH_ID         SERIAL PRIMARY KEY,
    DISH_NAME       VARCHAR(50),
    COST            INTEGER NOT NULL,
    CONSTRAINT MAX_COST
    CHECK (COST <= 10000)
);

CREATE TABLE BANQUETS.CUSTOMER(
    CUSTOMER_ID     SERIAL PRIMARY KEY,
    NAME            VARCHAR(50),
    SURNAME         VARCHAR(50),
    PHONE_NUMBER    VARCHAR(20)
);

CREATE TABLE BANQUETS.EVENT(
    EVENT_ID         SERIAL PRIMARY KEY,
    CUSTOMER_ID      INTEGER REFERENCES BANQUETS.CUSTOMER(CUSTOMER_ID),
    EVENT_TYPE       VARCHAR(50),
    EVENT_DTTM       TIMESTAMP NOT NULL,
    GUESTS_NUMBER    INTEGER NOT NULL,
    FLOOR            INTEGER NOT NULL,
    SEATING_TIME     TIME,
    FIRST_HOT_TIME   TIME,
    SECOND_HOT_TIME  TIME,
    END_TIME         TIME,
    BUFFET_TABLE_FLG BOOLEAN DEFAULT FALSE,
    SUM              INTEGER NOT NULL,
    PAYMENT_STATUS   BOOLEAN DEFAULT FALSE,
    CONSTRAINT MAX_GUESTS_NUMBER
    CHECK (GUESTS_NUMBER <= 200),
    CONSTRAINT FLOOR_NUMBER
    CHECK (FLOOR IN (1, 2))
);

CREATE TABLE BANQUETS.EMPLOYEE_X_EVENT(
    EMPLOYEE_ID     INTEGER REFERENCES BANQUETS.EMPLOYEE(EMPLOYEE_ID),
    EVENT_ID        INTEGER REFERENCES BANQUETS.EVENT(EVENT_ID),
    CONSTRAINT PAIR_KEY PRIMARY KEY(EMPLOYEE_ID, EVENT_ID)
);

CREATE TABLE BANQUETS.TABLE(
    TABLE_ID        VARCHAR(5) PRIMARY KEY,
    EVENT_ID        INTEGER REFERENCES BANQUETS.EVENT(EVENT_ID),
    PLACES_NUMBER   INTEGER NOT NULL,
    CONSTRAINT MAX_PLACES_NUMBER
    CHECK (PLACES_NUMBER <= 10)
);

CREATE TABLE BANQUETS.TABLE_X_DISH(
    TABLE_ID        VARCHAR(5) REFERENCES BANQUETS.TABLE(TABLE_ID),
    DISH_ID         INTEGER REFERENCES BANQUETS.DISH(DISH_ID),
    DISHES_NUMBER   INTEGER NOT NULL,
    DISH_TYPE       VARCHAR(50),
    CONSTRAINT PAIR_KEY_2 PRIMARY KEY(TABLE_ID, DISH_ID),
    CONSTRAINT ALL_DISH_TYPES
    CHECK (DISH_TYPE IN ('общее', 'салат', 'первое горячее', 'второе горячее'))
);


create table banquets.staff(
    staff_id INTEGER,
    name VARCHAR(50),
    salary integer,
    email VARCHAR(50),
    birthday
)

