--Функция маскирования--

CREATE OR REPLACE FUNCTION CREATE_MASK(PHONE TEXT)
RETURNS TEXT AS
$$
    DECLARE
        SIZE INT := LENGTH(PHONE);
        MASK_START TEXT := SUBSTRING(PHONE FROM 1 FOR 2);
        MASK_END TEXT := SUBSTRING(PHONE FROM SIZE - 1 FOR SIZE);

    BEGIN
        FOR I IN 3 .. SIZE - 2
            LOOP
                MASK_START = CONCAT(MASK_START, '*');
            END LOOP;

        MASK_START = CONCAT(MASK_START, MASK_END);

        RETURN MASK_START;
    END;
$$
LANGUAGE PLPGSQL;

--Обновление таблицы "блюдо на столе"--

CREATE OR REPLACE PROCEDURE ADD_DISH(NEW_TABLE_ID VARCHAR(5), NEW_DISH_ID INTEGER,
                                     NEW_DISHES_NUMBER INTEGER, NEW_DISH_TYPE VARCHAR(50),
                                     NEW_EVENT_ID INTEGER)
AS $$
    BEGIN
        IF NOT EXISTS (SELECT DISTINCT TABLE_ID
            FROM BANQUETS.TABLE
            WHERE TABLE_ID = NEW_TABLE_ID)
        THEN RETURN;
        END IF;

        IF NOT EXISTS (SELECT DISTINCT DISH_ID
            FROM BANQUETS.DISH
            WHERE DISH_ID = NEW_DISH_ID)
        THEN RETURN;
        END IF;

        IF NEW_DISHES_NUMBER IS NULL OR NEW_DISHES_NUMBER = 0
        THEN RETURN;
        END IF;

        INSERT INTO BANQUETS.TABLE_X_DISH
        VALUES (NEW_TABLE_ID, NEW_DISH_ID,
                NEW_DISHES_NUMBER, NEW_DISH_TYPE);
    END;
$$
LANGUAGE PLPGSQL;
